### PR TITLE
Add Vite

### PR DESCRIPTION
**Pull request by enzonotario**
Hi Henry!

I'm here with an initial Vite setup. Please take a look.

I don't really like to have the dev script as `.js`, but it wasn't *easy* to convert to TypeScript.

Thanks!

### CODE REVIEW

**Comment by henryhale** [comment]
Hey @enzonotario,

I appreciate your contribution and effort you've put into this library. Thank you!

I've taken the time to review the changes you made, and while I appreciate your work, I must mention that  according to this (https://github.com/henryhale/xterminal/pull/11#issuecomment-1631579330), I expected changes implementing a development server running a demo app so that it eases the development process with testing new features, debugging and more.
However, I believe there's an opportunity to improve the project further. 

I have been comparing these options () and found out that the benefits of rollup including optimized production builds outweigh vite's library mode which only handles syntax tranforms by default. Rollup offers a focused directory structure, which helps maintain a clean and organized codebase.

To explore the potential benefits of Rollup, I suggest setting up a dev server to serve the demo folder with an example application using Rollup. This will allow us to assess the advantages it brings to our project and make an informed decision on bundling approach. 

Some of my fIndings: 
- package.json and pnpm-lock.yaml are conflicting (the project is using pnpm) 
- vitejs builds only target browsers that support es modules by default (builds will not be supported by some browsers) 
- @types/node is for nodejs applications using typescript

Once again, thank you for your efforts and contribution.

**Comment by enzonotario** [comment]
Hey @henryhale , thanks! I'm glad to help you with this amazing project (and the others you have). 

- I have resolved the conflicts.
- I have added '@types/node' since PhpStorm complains about it. But ok, I just removed it.
image

I would like to ask you:

1. Could you please clarify your expectations regarding "a development server running a demo app"? Currently, there is a dev script that runs the existing demo code:
image

2. Are you suggesting to use Rollup for the build process and Vite for development? Or would you prefer Rollup for both scenarios?

Thanks!

**Comment by henryhale** [comment]
Thanks @enzonotario!

To answer you, I am suggesting that we use Rollup for build process and Vite for development. This will enable us enjoy the benefits of both tools. 

So my expectation was: you were going to create a folder `demo` at the root of the project directory, add a basic example (rather than docs demo - its meant for new users to test the library in action).

```txt
xterminal
   |- .github
   |- .husky
   |- ...
   |- demo
      |- index.html
      |- main.js
      |- styles.css
   |- docs
   |- source
   |- ...
```

With reference to the current master branch, I was also hoping that you would install `vite` as a dev dependency. Also install `concurrently` to enable us run  `tsc -w`,  `rollup -c -w` and `vite demo` in the same process.

```sh
"dev": "concurrently \"tsc -w\" \"rollup -c -w\" \"vite demo\""
```

Please let me know what you think.

Thanks again!

**Comment by enzonotario** [comment]
Hi @henryhale !

I think it's a nice approach. I haven't worked in this way before, but it looks good to me.

I have made the changes. Please take a look.

Thanks!

**Comment by henryhale** [comment]
Hey 👋

I just tested it and everything looks fine. 

I am kindly requesting you to add the `pnpm dev` command as number 4 in the _development > setup_ section of the `README.md`. It will help others have ease getting started with development.

Thanks!

**Comment by enzonotario** [comment]
Hey @henryhale , done!

Thank you so much!

**Pull request merged**
